FROM clojure AS builder

RUN mkdir -p /todogo/
ADD . /todogo/
WORKDIR /todogo/

# RUN rm -Rf resources/public/js/compiled
RUN lein cljsbuild once min
# RUN lein less once

FROM node:13.12.0-alpine as jsbuild

ADD . /todogo/
WORKDIR /todogo/

RUN npm install less -g
RUN lessc /todogo/src/less/site.less /todogo/resources/public/css/site.css

FROM nginx:stable-alpine
COPY ./nginx-site.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /todogo/resources/public/ /usr/share/nginx/html
COPY --from=jsbuilder /todogo/resources/public/css/site.css /usr/share/nginx/html/css/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
