FROM clojure AS builder

RUN mkdir -p /todogo/
ADD . /todogo/
WORKDIR /todogo/

# RUN rm -Rf resources/public/js/compiled
RUN lein cljsbuild once min
RUN lein less once


FROM nginx:stable-alpine
COPY ./nginx-site.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /todogo/resources/public/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
