version: '2'

services:

  web:
    container_name: web
    restart: always
    build: .
    env_file: .environment
    volumes:
      - .:/todogo/
    expose:
      - "3449/tcp"
    ports:
      - "3449:3449"
    command: lein figwheel dev
