version: '2'

services:
  api:
    container_name: api
    restart: always
#    build: ./docker/api
    image: kgantsov/todogo_api:latest
    env_file: .environment
#    volumes:
#      - ./docker/api/:/app/
    expose:
      - "8080/tcp"
    ports:
      - "8080:8080"
    links:
      - cockroach:cockroach
    depends_on:
      - cockroach
    command: /app/todogo

#  postgres:
#    container_name: postgres
#    restart: always
#    build: ./docker/postgres
#    volumes:
#      - postgresdatavolume:/var/lib/postgresql
#    ports:
#      - "5432:5432"
#    expose:
#      - "5432/tcp"

  cockroach:
    container_name: cockroach
    restart: always
    image: cockroachdb/cockroach:latest
    volumes:
      - cockroachdatavolume:/cockroach/cockroach-data
    ports:
      - "26257:26257"
    expose:
      - "26257/tcp"
    command: start --insecure

  psql:
    container_name: psql

    image: jbergknoff/postgresql-client

  web:
    container_name: web
    restart: always
    image: kgantsov/todogo_cljs:latest
    env_file: .environment
    volumes:
      - ./resources/public/:/public/
    expose:
      - "80/tcp"
    ports:
      - "80:80"
    links:
      - api:api
    depends_on:
      - api

volumes:
  postgresdatavolume:
    driver: local

  cockroachdatavolume:
      driver: local
